### ISSUE TITLE
Darstellungsfehler auf der Startseite

### ISSUE THREAD

**Issue by fetmo** [football-betting/symfony4#13]
**Problem**
Bei Aufruf der Startseite muss der Application-Cache gelöscht werden, sonst werden die neuen Styling und JS-Files nicht gezogen. Fehlen die neuen JS-Scripts können keine Ergebnisse gespeichert werden.

**Lösungsvorschlag**
Hier sollte ein neuer Dateiname erzeugt werden, um das Browsercaching zu umgehen.
![image](https://user-images.githubusercontent.com/19923729/41525890-c41616de-72e2-11e8-974c-18897ccb425a.png)

**Comment by Klizzy** [comment]
Danke für das Erstellen der Issue. Der Fix ist bereits ausgespielt 😁
