### ISSUE TITLE
Negative Einträge in Ergebnis

### ISSUE THREAD

**Issue by fetmo** [football-betting/symfony4#14]
**Problem**
Im Frontend sind negative Beträge auswählbar und auch speicherbar (s. Screenshot). Wird die Seite neu geladen ist kein Ergebnis gespeichert worden.

![image](https://user-images.githubusercontent.com/19923729/41526075-4f92c860-72e3-11e8-8fe2-159ec034b768.png)

**Comment by Klizzy** [comment]
Danke für die Issue. Das Eingeben von negativen Zahlen ist nun nicht mehr möglich und die Fehlermeldung wird wieder korrekt ausgeben.
